name: Mockgee.com - CI/CD

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Install Node package
      run: npm install
      
    - name: Build the project
      run: npm run build

    - name: Delete existing build JS files
      run: AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} aws s3 rm s3://${{ secrets.S3_BUCKET_NAME }}/js --recursive

    - name: Delete existing build CSS files  
      run: AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} aws s3 rm s3://${{ secrets.S3_BUCKET_NAME }}/css --recursive

    - name: Deploy to AWS S3
      run: AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} aws s3 cp dist s3://${{ secrets.S3_BUCKET_NAME }}/ --recursive 
